---
title: "Asylum seeker arrivals and migration policy events in 2021"
author: "Kendra Lyons"
date: '2022-04-15'
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
library(ggrepel)
library(ggthemes)
library(knitr)
library(tidyverse)
opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

## Data Dates: 1/26/21-1/20/22

Data for this project were collected by volunteers and staff at Casa Alitas Welcome Center in Tucson, Arizona. 

```{r, echo=FALSE}
policy_events <- read_csv("data/migration_policy_events_timeline_2021_ selected.csv", skip = 2) %>%
  mutate(date = parse_date(date, format = "%m/%d/%Y"),
         category = category) #%>% 

key_policy_events <- policy_events %>%
  filter(category %in% c('MPP ("Remain in Mexico")', 
                         'Temporary Protected Status',
                         'Title 42', 
                         'Detention')) %>%
  mutate(category = factor(category, levels=c('MPP ("Remain in Mexico")', 
                                              'Temporary Protected Status', 
                                              'Title 42',
                                              'Detention')))
  
arrival_counts <- read_csv("data/arrival_date_counts_1.20.csv") %>%
  rename("date" = arrival_date) %>%
  add_row(date = as.Date("2021-01-20"), n = 0, seven_avg = 0, .before = 1) %>% # add row for first event
  left_join(key_policy_events)%>%
  mutate(category = category)

group_counts <- read_csv("data/groups_limited_1.20.csv") %>%
  filter(number_in_party != 0)%>%
  rename("country" = country1)

countries <- read_csv("data/country_counts_1.20.csv")%>%
  drop_na(country)

```




## Visualize

```{r, echo=FALSE}
# set plot theme
theme_set(theme_minimal(12))

# plot timeline of daily arrivals with selected policy change labels
arrival_counts  %>%
  ggplot(aes(x = date,
             y = n,
             label = description)) +
  geom_col(fill ="grey", show.legend = FALSE) +
  geom_line(aes(y = seven_avg), 
            color = 'black', size = .6) +
  geom_label_repel(aes(color = category),
                   na.rm = TRUE,
                   size = 2,
                   show.legend = FALSE,
                   nudge_y = 170,
                   max.overlaps = 11) +
  geom_point(aes(color = category),
             data = arrival_counts %>% filter(!is.na(description)),
             show.legend = FALSE) +
  scale_x_date(date_breaks="1 month", 
               date_labels="%b",
               expand = c(.02,-.02)) +
  scale_color_colorblind() +
  labs(x = element_blank(),
       y = "Daily Shelter Arrivals",
       title = "Migration and policy events in 2021",
       subtitle = "with Casa Alitas daily arrivals") 

key_policy_events %>%
  kable(caption = "Immigration Policy Changes in 2021 (Source: Investigative Reporting Workshop)")
  
```


```{r, echo=FALSE}
# visualize policy changes & 7-day-rolling mean of daily arrivals
arrival_counts  %>%
  ggplot(aes(x = date,
             y = n,
             label = description)) +
  geom_line(aes(y = seven_avg), 
            color = 'darkgrey', size = .8) +
  geom_vline(data = key_policy_events, 
             aes(xintercept = date, 
                 color = category),
             na.rm = TRUE,
             size = .75) +
  labs(title = "Migration policy changes affected daily shelter arrivals in 2021",
       color = element_blank(), 
       x = element_blank(), 
       y = "Daily Shelter Arrivals") +
  theme(legend.position = "top", legend.justification = -.5) +
  scale_color_colorblind() +
  scale_x_date(date_breaks="1 month", 
               date_labels="%b",
               expand = c(.02,-.02))

```


```{r, echo=FALSE}
group_counts %>% 
  ggplot(aes(x = arrival_date, 
             y = number_in_party)) +
  geom_jitter(aes(size = number_in_party), 
              alpha = .1, na.rm = TRUE, 
              show.legend = FALSE) +
  scale_x_date(date_breaks="1 month", 
               date_labels="%b",
               expand = c(.02,-.02)) +
  geom_vline(data = key_policy_events, 
             aes(xintercept = date, 
                 color = category),
             na.rm = TRUE,
             size = .75) +
  labs(title ="Migration policy shifts affected individuals and groups differently", 
       x = element_blank(), 
       y = "Group Size",
       color = element_blank()) +
  scale_color_colorblind() +
  theme(legend.position = "top", legend.justification = -.5)


# migration policy shifts affect individuals and groups differently
```


```{r}

# Arrivals by country over time dot plot
some_countries <- countries$country[countries$n > 3]

group_counts %>%
  filter(country %in% some_countries) %>% # get rid of NAs! 
  ggplot(aes(x = arrival_date, 
             y = factor(country, rev(countries$country)))) +
  geom_point(alpha = .1) +
  geom_vline(data = key_policy_events, 
             aes(xintercept = date, 
                 color = category),
             na.rm = TRUE,
             size = .75) +
  theme(legend.position = "top", legend.justification = 1) + #, legend.direction legend.text.align = -1, 
  labs(title = "Migration policy shifts affected nationalities differently",
       x = element_blank(), 
       y = element_blank(),
       color = element_blank()) +
  scale_x_date(date_breaks = "1 month", 
               date_labels = "%b",
               expand = c(.02,-.02)) +
  scale_color_colorblind()

```

Further Resources:

- https://investigativereportingworkshop.org/news/timeline-bidens-immigration-policy/

- https://cmsny.org/biden-immigration-executive-actions/

- https://www.pewresearch.org/fact-tank/2022/01/11/key-facts-about-u-s-immigration-policies-and-bidens-proposed-changes/

- https://www.boundless.com/blog/biden-immigration-tracker/

- https://immpolicytracking.org/home/

- https://www.lawfareblog.com/president-bidens-immigration-executive-actions-recap#Asylum

- https://www.migrationpolicy.org/article/court-order-relaunch-remain-in-mexico

