---
title: "Annotated Arrivals Timeline"
author: "Kendra Lyons"
date: '2022-04-15'
output: html_document
---

```{r setup, include=FALSE}
library(ggrepel)
library(ggthemes)
library(knitr)
library(tidyverse)
opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

## Data

```{r}
policy_events <- read_csv("data/migration_policy_events_timeline_2021 - Sheet1.csv", skip = 2) %>%
  mutate(date = parse_date(date, format = "%m/%d/%Y"),
         category = factor(category)) #%>% 
  #filter(category %in% c('MPP ("Remain in Mexico")', 'Title 42')) # change to see different labels (, 'Temporary Protected Status')
key_policy_events <- policy_events %>%
  filter(category %in% c('MPP ("Remain in Mexico")', 
                         'Title 42', 
                         'Temporary Protected Status')) #%>%rename("arrival_date" = date)
  

arrival_counts <- read_csv("data/arrival_date_counts_1.20.csv") %>%
  rename("date" = arrival_date) %>%
  add_row(date = as.Date("2021-01-20"), n = 0, seven_avg = 0, .before = 1) # add row so first event isn't missed

arrival_counts <- arrival_counts %>%
  left_join(key_policy_events)

group_counts <- read_csv("data/groups_limited_1.20.csv") %>%
  filter(number_in_party != 0)

```
## Visualize

```{r}
group_counts %>% 
  ggplot(aes(x = arrival_date, 
             y = number_in_party)) +
  geom_jitter(aes(size = number_in_party), 
              alpha = .1, na.rm = TRUE, 
              show.legend = FALSE) +
  scale_x_date(date_breaks="1 month", 
               date_labels="%b") +
  geom_vline(data = key_policy_events, 
             aes(xintercept = date, 
                 color = category),
             na.rm = TRUE) +
  # geom_text(data = key_policy_events, 
  #           aes(label = category, x = date)) +
  #theme(legend.position = "top", # not working!!
        #legend.direction = "horizontal") +
  scale_color_colorblind() +
  labs(title ="Migration policy shifts impact asylum seekers traveling alone and in groups differently.", 
       x = element_blank(), 
       y = "Group Size",
       color = "Type of Policy Shift") +
  theme_minimal()

```


```{r}
# plot timeline of daily arrivals with selected policy change labels

arrival_counts  %>%
  ggplot(aes(x = date,
             y = n,
             label = description)) +
  geom_col(color = "white") +
  geom_line(aes(y = seven_avg), 
            color = 'black', size = .6) +
  geom_label_repel(aes(color = category),
                   na.rm = TRUE,
                   size = 2,
                   show.legend = FALSE,
                   nudge_y = 100,
                   max.overlaps = 13) +
  geom_point(data = arrival_counts %>% filter(!is.na(description)), 
             aes(color = category),
             show.legend = FALSE)+
  scale_x_date(date_breaks="1 month", 
               date_labels="%b",
               limits = c(start = as.Date("2021-01-18"), 
                          end = as.Date("2022-01-22"))) +
  scale_color_colorblind() +
  theme_minimal() +
  labs(title = "Migration policy shifts contribute to erratic daily arrivals",
       x = element_blank(),
       y = "Daily Shelter Arrivals") 
  
```

